### ISSUE TITLE
Inline Query Analyzer Control Add-in and Inline Query Analyzer Page

### ISSUE THREAD

**Issue by msnraju** [msnraju/inline-query#10]
A Control Add-in that accepts Inline Queries (with syntax highlights) and shows results in a Grid

Javascript libraries:
[ag-Grid](https://www.ag-grid.com/) for showing grids, and [highlightjs](https://highlightjs.org) for syntax highlights

**Comment by pri-kise** [comment]
Maybe https://github.com/grid-js/gridjs could be an option too, since it is fully open source and free of charge

**Comment by msnraju** [comment]
> Maybe https://github.com/grid-js/gridjs could be an option too, since it is fully open source and free of charge

Hi pri-kise,
Thanks for your suggestion. Considering future needs, I have used ag-Grid. Its implemented now, your feedback on "Inline Query Analyzer" page will be appreciated.
